# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='ActionReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_value', models.CharField(max_length=255)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_reference_actions', to='erm_automation.Action')),
            ],
            options={
                'verbose_name': 'Action Reference',
                'verbose_name_plural': 'Action References',
            },
        ),
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_reference_value', models.CharField(max_length=255)),
                ('action_reference_value', models.CharField(max_length=255)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_actions', to='erm_automation.Action')),
                ('action_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_action_references', to='erm_automation.ActionReference')),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_value', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='erm_automation.Event')),
            ],
            options={
                'verbose_name': 'Event Reference',
                'verbose_name_plural': 'Events References',
            },
        ),
        migrations.AddField(
            model_name='automation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_events', to='erm_automation.Event'),
        ),
        migrations.AddField(
            model_name='automation',
            name='event_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_event_references', to='erm_automation.EventReference'),
        ),
    ]
