# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0003_remove_eventreference_event_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreference',
            name='event_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreference',
            name='event_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
