# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0008_auto_20171207_1144'),
        ('erm_automation', '0004_auto_20171117_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_automations', to='erm_room.Room'),
        ),
    ]
