# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0005_automation_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreference',
            name='button_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventreference',
            name='poll_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventreference',
            name='trigger_event_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventreference',
            name='trigger_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventreference',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
