# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0006_auto_20171212_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionreference',
            name='action_value',
        ),
    ]
