# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0008_auto_20171207_1144'),
        ('erm_automation', '0007_remove_actionreference_action_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionreference',
            name='blink_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='clue_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_reference_puzzles', to='erm_room.Puzzles'),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='room_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_reference_room_images', to='erm_room.RoomImages'),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='script_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='script_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_reference_sounds', to='erm_room.Sounds'),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='time_to_adjust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_reference_videos', to='erm_room.Videos'),
        ),
    ]
