# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0008_auto_20171212_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='action',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='action_reference',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='action_reference_value',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='automation',
            name='event_reference_value',
        ),
    ]
