# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0009_auto_20171213_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='action_reference',
            field=models.ManyToManyField(related_name='automations_action_references', to='erm_automation.ActionReference'),
        ),
    ]
