# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0011_eventreference_event_sec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreference',
            name='event_max',
        ),
    ]
