# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0014_auto_20180418_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionreference',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actionreference',
            name='scene_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
