# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0015_auto_20181010_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionreference',
            name='scene_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
