# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-18 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_automation', '0016_auto_20181010_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionreference',
            name='light_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
