# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 13:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_billing', '0002_billing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='exp_month',
            field=models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Month must be numeric and contain 2 digit', regex='^\\d{1,10}$')]),
        ),
        migrations.AlterField(
            model_name='billing',
            name='exp_year',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Year must be numeric and contain 4 digit', regex='^\\d{1,10}$')]),
        ),
    ]
