# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 15:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_billing', '0004_auto_20171218_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='cvc',
            field=models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Cvc must be numeric and contain 3 digit', regex='^\\d{1,10}$')]),
        ),
    ]
