# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 09:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_billing', '0005_auto_20180412_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='card_no',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Card No must be numeric and contain 16-20 digit', regex='^(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})$')]),
        ),
    ]
