# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-27 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_billing', '0006_auto_20180418_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user',
        ),
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
