# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_clues', to='erm_room.Room')),
            ],
            options={
                'verbose_name': 'Clue',
                'verbose_name_plural': 'Clues',
            },
        ),
    ]
