# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0005_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_name', models.CharField(max_length=255)),
                ('reset_instructions', models.TextField(blank=True, null=True)),
                ('damage_or_notes', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_puzzles', to='erm_room.Room')),
            ],
            options={
                'verbose_name_plural': 'Puzzles',
                'verbose_name': 'Puzzle',
            },
        ),
    ]
