# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import erm_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0008_auto_20171207_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='failed_audio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
    ]
