# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import erm_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0009_auto_20180316_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='audio_alert',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='fail_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='soundtrack',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='success_audio',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='success_video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='room',
            name='video_brief',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
    ]
