# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0011_auto_20180316_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='clue_count_img_width',
            field=models.IntegerField(blank=True, default=72, null=True),
        ),
    ]
