# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0013_auto_20180412_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_tablet_room',
            field=models.BooleanField(default=False),
        ),
    ]
