# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erm_room', '0015_remove_room_is_tablet_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzlesSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_time', models.CharField(blank=True, max_length=255, null=True)),
                ('max_time', models.CharField(blank=True, max_length=255, null=True)),
                ('mean_time', models.CharField(blank=True, max_length=255, null=True)),
                ('median_time', models.CharField(blank=True, max_length=255, null=True)),
                ('play_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_puzzles_summary', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_puzzles_summary', to='erm_room.Puzzles')),
            ],
            options={
                'verbose_name': 'PuzzleSummary',
                'verbose_name_plural': 'PuzzlesSummary',
            },
        ),
    ]
