# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0016_puzzlessummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlessummary',
            name='solved_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
