# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0017_puzzlessummary_solved_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzlessummary',
            name='room',
        ),
    ]
