# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0018_remove_puzzlessummary_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlessummary',
            name='puzzle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_puzzles_summary', to='erm_room.Puzzles'),
        ),
    ]
