# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0019_puzzlessummary_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzlessummary',
            name='play_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
