# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0020_puzzlessummary_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_tablet_room',
            field=models.BooleanField(default=False),
        ),
    ]
