# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-23 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0021_room_is_tablet_room'),
        ('erm_room', '0023_auto_20180522_1452'),
    ]

    operations = [
    ]
