# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-26 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0024_merge_20180523_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_guide_room',
            field=models.BooleanField(default=False),
        ),
    ]
