# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0024_merge_20180523_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('clues_given', models.CharField(max_length=255)),
                ('game_time', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('consumed_time', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('no_of_players', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_played', to='erm_room.Room')),
            ],
        ),
    ]
