# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-26 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0025_room_is_guide_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_scoring', models.BooleanField(default=False)),
                ('starting_score', models.IntegerField(blank=True, null=True)),
                ('score_title', models.CharField(blank=True, max_length=255, null=True)),
                ('always_reduce', models.BooleanField(default=False)),
                ('penalty_per_minute', models.IntegerField(blank=True, null=True)),
                ('is_penalize', models.BooleanField(default=False)),
                ('end_game_at_zero', models.BooleanField(default=False)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_scoring', to='erm_room.Room')),
            ],
            options={
                'verbose_name': 'Clue',
                'verbose_name_plural': 'Clues',
            },
        ),
    ]
