# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-26 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0026_scoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoring',
            name='room',
        ),
    ]
