# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0027_remove_scoring_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_scoring', to='erm_room.Room'),
        ),
    ]
