# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-26 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0029_auto_20180626_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoring',
            options={'verbose_name': 'Scoring', 'verbose_name_plural': 'Scorings'},
        ),
    ]
