# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0025_gameresults'),
        ('erm_room', '0030_auto_20180626_1403'),
    ]

    operations = [
    ]
