# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 13:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0031_merge_20180703_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin_pin',
            field=models.IntegerField(default=1234, validators=[django.core.validators.MaxLengthValidator(9999)]),
            preserve_default=False,
        ),
    ]
