# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0032_room_admin_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='final_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='game_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='hint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='hint_tap_exit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='hints_full_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_timer_visible',
            field=models.BooleanField(default=False),
        ),
    ]
