# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-04 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0033_auto_20180703_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_timer_milliseconds',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='hint_tap_exit',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='hints_full_screen',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='start_timer_after_video_brief',
            field=models.BooleanField(default=True),
        ),
    ]
