# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0035_auto_20180704_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='final_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
