# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 06:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0036_auto_20180705_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin_pin',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
