# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0037_auto_20180705_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin_pin',
            field=models.CharField(max_length=4),
        ),
    ]
