# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-06 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0038_auto_20180705_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='fail_font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='fail_hide_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='fail_timer_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='success_font_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='success_hide_timer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='success_timer_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
