# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0039_auto_20180706_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='game_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_timer_visible',
        ),
        migrations.RemoveField(
            model_name='room',
            name='success_font_size',
        ),
    ]
