# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-10 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import erm_room.models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0041_auto_20180707_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleClue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clue_type', models.CharField(blank=True, max_length=255, null=True)),
                ('clue_uploads_options', models.CharField(choices=[('Text', 'text'), ('Image', 'image'), ('Audio', 'audio'), ('Video', 'video')], default='Text', max_length=255)),
                ('clue_textarea', models.TextField(blank=True, null=True)),
                ('clue_file_uploads', models.FileField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path)),
                ('clue_icon', models.ImageField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path)),
                ('clue_checkbox', models.BooleanField(default=False)),
                ('score_penatly', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='puzzles',
            name='dashboard_icon',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=erm_room.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='puzzles',
            name='enabled_puzzle_clue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='fail_ending_type',
            field=models.CharField(choices=[('video ending', 'video ending'), ('text ending', 'text ending')], default='Video Ending', max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='success_ending_type',
            field=models.CharField(choices=[('video ending', 'video ending'), ('text ending', 'text ending')], default='Video Ending', max_length=255),
        ),
        migrations.AddField(
            model_name='puzzleclue',
            name='puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erm_room.Puzzles'),
        ),
    ]
