# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-19 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0043_auto_20180717_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleclue',
            name='score_penatly',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
