# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0045_auto_20180731_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzleclue',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='puzzleclue',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
