# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-08 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erm_room', '0047_philipgroupsandscenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='philipgroupsandscenes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_philip_group_and_scene', to=settings.AUTH_USER_MODEL),
        ),
    ]
