# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0048_philipgroupsandscenes_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('time_remaining', models.IntegerField(default=3600)),
                ('no_of_players', models.IntegerField(default=4)),
                ('num_clues', models.IntegerField(default=0)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('game_time', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('consumed_time', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_records', to='erm_room.Room')),
            ],
        ),
        migrations.RemoveField(
            model_name='gameresults',
            name='room',
        ),
        migrations.DeleteModel(
            name='GameResults',
        ),
    ]
