# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-22 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_room', '0049_auto_20190522_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamerecord',
            old_name='no_of_players',
            new_name='num_players',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='consumed_time',
        ),
        migrations.RemoveField(
            model_name='gamerecord',
            name='game_time',
        ),
    ]
