# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=140, verbose_name='Subject')),
                ('message_body', models.TextField(verbose_name='Body')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('replied_date', models.DateTimeField(blank=True, null=True, verbose_name='replied at')),
                ('creator_deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Sender deleted date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_messages', to='messages_system.Message', verbose_name='Parent message')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='read date')),
                ('recipient_deleted_date', models.DateTimeField(blank=True, null=True, verbose_name='Recipient deleted date')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to='messages_system.Message', verbose_name='Recipient')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
        ),
    ]
