# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 05:48
from __future__ import unicode_literals

from django.db import migrations
from helpers.timezones import TIMEZONES


def load_data(apps, schema_editor):
    Timezone = apps.get_model("erm_business", "Timezone")

    for timez in TIMEZONES:
        Timezone.objects.get_or_create(timezone=timez[0])


class Migration(migrations.Migration):

    dependencies = [
        ('erm_business', '0002_business_user'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
