# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erm_business', '0004_auto_20180503_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location_name',
        ),
    ]
