# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-10 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erm_business', '0005_remove_business_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
