# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erm_room', '0024_merge_20180523_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entries_to_display', models.IntegerField(default=0)),
                ('background_color', models.CharField(default='#000000', max_length=255)),
                ('column_background_color', models.CharField(default='#333333', max_length=255)),
                ('font_color', models.CharField(default='#ffffff', max_length=255)),
                ('scroll_speed', models.IntegerField(default=4)),
                ('refresh_interval', models.IntegerField(default=60)),
                ('display_time_elapsed', models.BooleanField(default=True)),
                ('escape_rate_label', models.CharField(default='Escape Rate', max_length=255)),
                ('week_label', models.CharField(default='Current Week', max_length=255)),
                ('month_label', models.CharField(default='Current Month', max_length=255)),
                ('year_label', models.CharField(default='Current Year', max_length=255)),
                ('all_time_label', models.CharField(default='All Time', max_length=255)),
                ('no_winners_yet_label', models.CharField(default='No winners...', max_length=255)),
                ('room_name_font_size', models.IntegerField(default=94)),
                ('room_escape_rate_font_size', models.IntegerField(default=94)),
                ('column_header_font_size', models.IntegerField(default=94)),
                ('team_name_font_size', models.IntegerField(default=34)),
                ('time_font_size', models.IntegerField(default=34)),
                ('image_height', models.IntegerField(default=34)),
                ('live_view_font', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_live_view_fonts', to='erm_room.LiveViewFont')),
            ],
            options={
                'verbose_name': 'Leaderboard',
                'verbose_name_plural': 'Leaderboards',
            },
        ),
    ]
