# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='column_alltime_header_color',
            field=models.CharField(default='#28b779', max_length=255),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='column_body_color',
            field=models.CharField(default='#ffffff', max_length=255),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='column_month_header_color',
            field=models.CharField(default='#17a668', max_length=255),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='column_week_header_color',
            field=models.CharField(default='#2194ca', max_length=255),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='column_year_header_color',
            field=models.CharField(default='#da9627', max_length=255),
        ),
    ]
