# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20180601_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='column_font_color',
            field=models.CharField(default='#000000', max_length=255),
        ),
    ]
